---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:

    - name: "install python for Ansible."
      apt:
        name: python3
        state: latest
        update_cache: yes

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - NODE_ENV: production
    - ENVIRONMENT: production
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    - TYPEORM_HOST: postgres.csjffbcmdsxv.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: Olatejumi9621..
    - TYPEORM_DATABASE: postgres
    - TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    - TYPEORM_MIGRATIONS_DIR: ./src/migrations

  roles:
    - configure-server
   